### ISSUE TITLE
ArgumentException: The output Mat object has to be of the same size

### ISSUE THREAD

**Issue by samw3** [EnoxSoftware/OpenCVForUnity#1]
I'm getting the following error when trying to run the WebCamTextureToMatSample example.

I'm on Unity  4.6.1f1 on a Macbook Air OS X 10.10.2

ArgumentException: The output Mat object has to be of the same size
OpenCVForUnity.Utils.WebCamTextureToMat (UnityEngine.WebCamTexture webCamTexture, OpenCVForUnity.Mat mat, UnityEngine.Color32[] bufferColors) (at Assets/OpenCVForUnity/org/opencv/unity/Utils.cs:360)
OpenCVForUnitySample.WebCamTextureToMatSample.Update () (at Assets/OpenCVForUnity/Samples/WebCamTextureToMatSample/WebCamTextureToMatSample.cs:101)

**Comment by Skval** [comment]
I has the same problem!

**Comment by Skval** [comment]
Ohh,,,Sorry, I must update :)

**Comment by EnoxSoftware** [comment]
After having set up Plugin, Plugin may work well when you reboot Unity.

**Comment by Skval** [comment]
All ok. Thank you!

**Comment by Skval** [comment]
So, say…what i must did when I have that error:

Found plugins with same names and architectures, Assets/OpenCVForUnity/Plugins/Android/libs/armeabi-v7a/libnative_camera_r4.1.1.so () and Assets/OpenCVForUnity/Plugins/Android/libs/x86/libnative_camera_r4.1.1.so (). Assign different architectures or delete the duplicate.
UnityEditor.AndroidPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.HostView:OnGUI()

**Comment by EnoxSoftware** [comment]
Please confirm ProjectSettings.
“OpenCVForUnity/Plugins/libs/armeabi-v7a/*.so” – Select platform Android and CPU ARMv7 in Inspector.
“OpenCVForUnity/Plugins/libs/x86/*.so” – Select platform Android and CPU x86 in Inspector.

**Comment by EdilsonJunior** [comment]
mine is also giving the same error size when I Execultar qualqer example. what to do?

**Comment by WuttipongMAD** [comment]
ArgumentException: The output Mat object has to be of the same size
OpenCVForUnity.Utils.texture2DToMat (UnityEngine.Texture2D texture2D, OpenCVForUnity.Mat mat) (at Assets/OpenCVForUnity/org/opencv/unity/Utils.cs:521)
OpenCVForUnitySample.DrawingSample.Start () (at Assets/OpenCVForUnity/Samples/DrawingSample/DrawingSample.cs:23)
