### ISSUE TITLE
How can I do matrix multiplication?

### ISSUE THREAD

**Issue by rabienrose** [EnoxSoftware/OpenCVForUnity#10]
I try to use A*B, but the compiler say the operator * can not apply to Mat

**Comment by EnoxSoftware** [comment]
Multiplication of Mat is possible using Core.gemm() function.
http://stackoverflow.com/questions/27212167/unable-to-multiply-matrix-in-opencv-java

**Comment by rabienrose** [comment]
It seems work, thank you.
