### ISSUE TITLE
How to reduce frameRate in facedetection example?

### ISSUE THREAD

**Issue by Harshabajje** [EnoxSoftware/OpenCVForUnity#105]
How can i reduce the frame rate in FaceDtetctionExample. I tried changing this parameter, but I don't see any changes             ""webCamTextureToMatHelper.requestedFPS = 1 ; ""

**Comment by EnoxSoftware** [comment]
The value supported by the requestedFPS parameter of the WebCamTexture class depends on the hardware.
https://docs.unity3d.com/ScriptReference/WebCamTexture-requestedFPS.html

Also, Frame skipping can be easily implemented using ImageOptimizationHelper.
https://github.com/EnoxSoftware/OpenCVForUnity/blob/master/Assets/OpenCVForUnity/Examples/Advanced/PolygonFilterExample/PolygonFilterExample.cs
