### ISSUE TITLE
VideoCapture.Open() cannot open video files when its path contains non-ASCII characters 

### ISSUE THREAD

**Issue by cauosg** [EnoxSoftware/OpenCVForUnity#108]
This is an issue when opening a local video file from some paths containing Unicode characters such as Korean, Japanese, Chinese, etc.

As results of our testing, It seems that non-ASCII path is not available in VideoCapture.Open()

Could this problem be improved in the future? If not, we have to give up using OpenCVForUnity... Or is there any other solution to solve this?

**Comment by EnoxSoftware** [comment]
Unfortunately, OpenCV does not seem to support file paths containing Unicode.
You can also specify a relative file path, as in the following code.

Mat src = Imgcodecs.imread ("./Assets/StreamingAssets/pca_test1.jpg");

**Comment by iMaTzzz** [comment]
Are there any updates or workarounds about this ?

**Comment by EnoxSoftware** [comment]
It appears that opencv does not yet support Unicode paths.
https://github.com/opencv/opencv/issues/24491
