### ISSUE TITLE
Does OpenCVForUnity include?

### ISSUE THREAD

**Issue by Tharyn** [EnoxSoftware/OpenCVForUnity#11]
Does the package include the HDR processing?

Thanks,
T

**Comment by EnoxSoftware** [comment]
HDR method is implemented in "OpenCV for Unity based on OpenCV3.0.0".
http://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_merge_debevec.html

**Comment by Tharyn** [comment]
Thank you for the information I'll go ahead and buy the asset.

Nice work, I'm looking forward to digging into it.
