### ISSUE TITLE
"Free Trial" version cannot be imported into a Unity project.

### ISSUE THREAD

**Issue by sherlockat** [EnoxSoftware/OpenCVForUnity#113]
I don't know much about Unity. Please understand.
I am interested in "OpenCVForUnity". And I want to use the "Free Trial" version.

The "Free Trial" version is downloaded as a "Zip" extension file.
I can't import this file using the "Assets -> Import package" menu.

I changed the "zip" extension to "unitypackage" and imported it and got an error.
"All assets from this package are already in your project"

I want a way to import the "Free Trial" version into my Unity project.
Please Help me.

**Comment by sherlockat** [comment]
I am using Unity version "2021.1.12f1" and version "2018.1.2f1"

**Comment by EnoxSoftware** [comment]
After unzipping the zip file, could you import the unitypackage file into the project?
If you are using macOS, you may need to use an app made by 3rdParty to unzip the zip.

**Comment by sherlockat** [comment]
Yes. I am using MacOS. I implemented your advice. The package was imported successfully.
Thank you very much.
