### ISSUE TITLE
Videowriter doesn't work

### ISSUE THREAD

**Issue by Zumbalamambo** [EnoxSoftware/OpenCVForUnity#116]
I'm using the following code to create video writer in Android.

`        writer.open(Application.persistentDataPath + "/VideoWriterExample_output.m4v", VideoWriter.fourcc('D', 'V', 'I', 'X'), 30, new Size(640, 360));
`

Unfortunately `writer.isOpened() false` is being thrown everytime. How can I fix it?

**Comment by EnoxSoftware** [comment]
The VideoWriter class on the Android platform does not seem to support "VideoWriter.fourcc('D', 'V', 'I', 'X')".
https://github.com/EnoxSoftware/OpenCVForUnity/blob/master/Assets/OpenCVForUnity/Examples/MainModules/videoio/VideoWriterExample/VideoWriterExample.cs#L185-L189

**Comment by Zumbalamambo** [comment]
I still have the same problem! :(
