### ISSUE TITLE
call VideoCapture function on Android

### ISSUE THREAD

**Issue by mkstmyk** [EnoxSoftware/OpenCVForUnity#13]
To accelerate video capturing, I modified WebCamTextureToMatSample by using VideoCapture directly instead of using WebCamTexture.
It worked well on OSX, WIN, and iOS, but not on Android 6.
It just showed a black texture.

According to the old document below:
http://enoxsoftware.github.io/OpenCVForUnity/doc/html/class_open_c_v_for_unity_1_1_video_capture.html
it seems that VideoCapture is not supported for above Android 5.
However, I'm using the latest asset and there are no similar words in the latest document:
https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_video_capture.html

I appreciate if someone know whether VideoCapture is supported or not for Android in the latest asset.

**Comment by EnoxSoftware** [comment]
Thank you for your inquiry.

VideoCapture (int index) and open (int index) is not supported for Android.
https://enoxsoftware.com/opencvforunity/documentation/support-modules/

**Comment by mkstmyk** [comment]
Thank you for your reply, and sorry for missing the list of support-modules.
Are there any plan to support these functions on Android in the future release?
In my understanding, using WebCamTexture is slow as it needs to copy texture to OpenCV.
I appreciate if you know any other tricks to overcome this problem without using VideoCapture() and open().
