### ISSUE TITLE
DNNModule setInput function works in editor but crashes on android device

### ISSUE THREAD

**Issue by Tigran1983** [EnoxSoftware/OpenCVForUnity#137]
Hi dear team,

My custom trained model works well in Unity editor (windows) but crashes on mobile android device (crash on setInput(blob)).
I tried everything possible, with setpreferablebackend, target, e.t. No any solution found. Also I couldn't found example of OpencvDNN usage on android device (built from Unity).

Please let me know is this unsupported case or know issue?

Best Regards,
Tigran

**Comment by EnoxSoftware** [comment]
Could you send me the code and model you tried?
https://enoxsoftware.com/opencvforunity/contact/technical-inquiry/

**Comment by Tigran1983** [comment]
I sent needed info by the form you requested.

Regards,
Tigran

**Comment by Tigran1983** [comment]
Thank you very much for your support. Issue was in ONNX placement, as you mentioned in your resolution. I should place it in StreamingAssets and use Utils.getFilePath() function. That's good. Also want to mention that in comparison with Barracuda, inference on desktop is 2x faster with OpenCVDNN, but on mobile only 30% faster then Barracuda inference.
You can close issue.

Thanks and Best Regards,
Tigran
