### ISSUE TITLE
Couldn't load ONNX model with 2 inputs of different shapes

### ISSUE THREAD

**Issue by Tigran1983** [EnoxSoftware/OpenCVForUnity#139]
Hi dear team,

I couldn't load my ONNX model with 2 inputs of different shapes. I am trying with documented way - from Assets/StreamingAssets/dnn, and with Utils.GetFilePath. The other models with 1 input and no concat layer are working normally, but this one is not loading.
Please look what is specific in this model. Also, after your resolution, let me know how I can forward loaded model after mentioning input names with setInputsNames. I couldn't combine these two inputs of different shapes into one Mat/blob for passing through setInput function.
This is the link of ONNX model.

https://drive.google.com/file/d/1zmC_zO9um-SRlzK_7E6Ke9OaRFdD3khk/view?usp=sharing

Thanks in advance,
Best Regards,
Tigran

**Comment by EnoxSoftware** [comment]
I have tested the attached ONNX model in my environment with the following code and got the error when loading the model.

```
        //if true, The error log of the Native side OpenCV will be displayed on the Unity Editor Console.
        Utils.setDebugMode(true);

        string model_filepath = Utils.getFilePath("dnn/" + "2inputs_concat.onnx");
        Net net = Dnn.readNetFromONNX(model_filepath);

        Utils.setDebugMode(false);
```

```
dnn::readNetFromONNX_10() : OpenCV(4.5.5-dev) C:\Users\xxxxxx\opencv\modules\dnn\src\onnx\onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211220::ONNXImporter::handleNode'
Node[Concat@ai.onnx]:(model / concatenate / concat:0) parse error: OpenCV(4.5.5 - dev) C: \Users\xxxxxx\opencv\modules\dnn\src\layers\concat_layer.cpp:104: error: (-201:Incorrect size of input array) Inconsistent shape for ConcatLayer in function 'cv::dnn::ConcatLayerImpl::getMemoryShapes'
```

It seems that the Onnx model needs some kind of modification in order to load with OpenCV's Dnn class.
https://github.com/opencv/opencv/issues?q=%27cv%3A%3Adnn%3A%3AConcatLayerImpl%3A%3AgetMemoryShapes%27

**Comment by Tigran1983** [comment]
Thank you very much. I have to implicitly mention concatenation axis in keras, so OpenCV can map this layer. Also I could forward and get output from whole network.
Thanks for your quick look and feedback. You can close ticket.

Best Regards,
Tigran
