### ISSUE TITLE
Change Mat for input to keras model(ONNX) with channels_last

### ISSUE THREAD

**Issue by Tigran1983** [EnoxSoftware/OpenCVForUnity#141]
Hello dear team,

I am trying to pass Mat (which is RGB image with 3 channels) to keras model (ONNX format), but loaded model has channels_last data format, so my inference doesn't work. I couldn't find any way to change Mat format to channels last, even with definition of new Mat[1,height, width,channels] and make manual assignment of pixels row by row.

Please let me know how I can pass 3-channel RGB Mat to setInput() for ONNX model with channels_last data format.

Thanks in advance,
Tigran

**Comment by Tigran1983** [comment]
I got answer from Opencv.org forum for c++, then I tried in OpenCVForUnity:
sz = new int[] {1, rows, cols, channels};
Mat blob =mat.reshape(1, sz);
model.setInput(blob);

There are no any errors, model is working, I hope the results will be as expected.

Please approve that my code with reshape is changing channels place from first to last correctly ( 1,channels,rows,cols -> 1,rows,cols,channels).

Thanks in advance,
Tigran

**Comment by EnoxSoftware** [comment]
I haven't checked your script, so I can't say for sure.
In generally, here's how reshape RGB Mat into Mat[1,height,width,channels] format.

```
        // create Mat [h, w, c]
        Mat rgbMat = new Mat(2, 2, CvType.CV_8UC3);
        rgbMat.put(0, 0, new byte[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 });
        // 
        // [[[0, 1, 2], [3, 4, 5]],
        // [[6, 7, 8], [9, 10, 11]]]
        // 

        // reshape Mat [h, w, c] to [1, h, w, c]
        Mat inputMat = rgbMat.reshape(1, new int[] { 1, rgbMat.rows(), rgbMat.cols(), rgbMat.channels() });
```

**Comment by Tigran1983** [comment]
I think that's approve, your correct way is similar. Thank you very much for quick response.
I waste many time on this.

You can close the issue. 
Best Regards,
Tigran
