### ISSUE TITLE
DnnModule is not being detected in UWP 

### ISSUE THREAD

**Issue by bilawal-mahmood** [EnoxSoftware/OpenCVForUnity#145]
DnnModule is not being detected in UWP but working perfectly in windows. All other modules are working in UWP except Dnn. it is a paid version not  trial.  
![image](https://user-images.githubusercontent.com/39480452/175344605-57a7713e-3f43-406b-89ef-679b95aeecf4.png)

**Comment by EnoxSoftware** [comment]
The OpenCV Dnn module is not supported by the UWP platform of OpenCV C++, so there is no plan to be implemented by OpenCVforUnity for now.
https://github.com/opencv/opencv/blob/master/modules/dnn/CMakeLists.txt#L1-L3
https://enoxsoftware.com/opencvforunity/documentation/support-modules/
