### ISSUE TITLE
hardware optical zoom

### ISSUE THREAD

**Issue by dragan07-07** [EnoxSoftware/OpenCVForUnity#149]
Is there a way to do optical zoom using openCV?

**Comment by olokobayusuf** [comment]
No. Consider using [NatDevice](https://github.com/natmlx/NatDevice) instead. It is the only full-featured camera and microphone API for Unity, and it has an integration with OpenCV (I'm the founder of NatML, the company behind this API). See the [official integration example from EnoxSoftware](https://github.com/EnoxSoftware/NatDeviceWithOpenCVForUnityExample), and the [NatDevice docs](https://docs.natml.ai/natdevice/api/cameradevice#zoom-ratio).

**Comment by olokobayusuf** [comment]
[Here's an integration demo right in your browser](https://demo.natml.ai/@natml/natdevice-opencv).
