### ISSUE TITLE
MobileNetssdExample

### ISSUE THREAD

**Issue by mjnasir** [EnoxSoftware/OpenCVForUnity#17]
I am trying to get object detection via caffee model but whenever i try to do my unity editor gets crash.

**Comment by EnoxSoftware** [comment]
Are you using the following files?

MobileNetSSD_deploy.prototxt
https://github.com/chuanqi305/MobileNet-SSD/blob/master/MobileNetSSD_deploy.prototxt
dnn/MobileNetSSD_deploy.caffemodel
https://drive.google.com/open?id=0B3gersZ2cHIxRm5PMWRoTkdHdHc

**Comment by UnNeill** [comment]
I'm having problems getting this to run, also.

I'm using the two files mentioned above.
3058607249(checksum) 25036(bytes) MobileNet_deploy.prototxt
3242836829(checksum) 17028869(bytes) MobileNet_deploy.caffemodel

it seems to be related to the prototxt file and/or format?
on android i get this error at runtime:
'
04-12 15:25:24.590 12522-12574/com.cr3d.mssd E/libprotobuf-native: [libprotobuf ERROR /Users/satoo/opencv/android/opencv/3rdparty/protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format opencv_caffe.NetParameter: 7:1: Expected identifier, got: <

04-12 15:25:24.590 12522-12574/com.cr3d.mssd E/cv::error(): OpenCV(3.4.1-dev) Error: Unspecified error (FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: /storage/emulated/0/Android/data/com.cr3d.mssd/files/opencvforunity/dnn/MobileNetSSD_deploy.prototxt) in void cv::dnn::ReadNetParamsFromTextFileOrDie(const char*, opencv_caffe::NetParameter*), file /Users/satoo/opencv/android/opencv/modules/dnn/src/caffe/caffe_io.cpp, line 1145
04-12 15:25:24.590 12522-12574/com.cr3d.mssd E/org.opencv.dnn: dnn::readNetFromCaffe_10() : OpenCV(3.4.1-dev) /Users/satoo/opencv/android/opencv/modules/dnn/src/caffe/caffe_io.cpp:1145: error: (-2) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: /storage/emulated/0/Android/data/com.cr3d.mssd/files/opencvforunity/dnn/MobileNetSSD_deploy.prototxt in function void cv::dnn::ReadNetParamsFromTextFileOrDie(const char*, opencv_caffe::NetParameter*)


`

the first lines of the prototxt file seem correct, there is no "<" 

`name: "MobileNet"
input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 224
  dim: 224
}
layer {
  name: "conv0"
  type: "Convolution"
  bottom: "data"
`

have any suggestions?
thanks!

**Comment by EnoxSoftware** [comment]
Model files can be downloaded using this script.
https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/download_models.py

MobileNet_deploy.prototxt 29,353 bytes
MobileNet_deploy.caffemodel 23,147,564 bytes

**Comment by UnNeill** [comment]
Thanks! This all works for me now!

@EnoxSoftware I wanted to ask your advice/opinions of caffe or tensorflow with a webcam on android? your caffe example seems to perform the best of your object detection/localization demos.....
How should I ask this question? email? wiki? issue?
thanks!

**Comment by EnoxSoftware** [comment]
@UnNeill Could you send a question to Technical Inquiry?
https://enoxsoftware.com/opencvforunity/contact/technical-inquiry/
