### ISSUE TITLE
c++ to c# conversion of "real-time pose estimation" example

### ISSUE THREAD

**Issue by tv-gc** [EnoxSoftware/OpenCVForUnity#170]
Hi!

I am currently "porting" this example https://github.com/opencv/opencv/tree/4.x/samples/cpp/tutorial_code/calib3d/real_time_pose_estimation from c++ to c# but i am facing some difficulties in some parts and i would like to ask for some assistance if possible.

In PnPProblem.cpp, 

`void PnPProblem::set_P_matrix( const cv::Mat &R_matrix, const cv::Mat &t_matrix)
{
    // Rotation-Translation Matrix Definition
    P_matrix_.at<double>(0,0) = R_matrix.at<double>(0,0);
    P_matrix_.at<double>(0,1) = R_matrix.at<double>(0,1);
    P_matrix_.at<double>(0,2) = R_matrix.at<double>(0,2);
    P_matrix_.at<double>(1,0) = R_matrix.at<double>(1,0);
    P_matrix_.at<double>(1,1) = R_matrix.at<double>(1,1);
    P_matrix_.at<double>(1,2) = R_matrix.at<double>(1,2);
    P_matrix_.at<double>(2,0) = R_matrix.at<double>(2,0);
    P_matrix_.at<double>(2,1) = R_matrix.at<double>(2,1);
    P_matrix_.at<double>(2,2) = R_matrix.at<double>(2,2);
    P_matrix_.at<double>(0,3) = t_matrix.at<double>(0);
    P_matrix_.at<double>(1,3) = t_matrix.at<double>(1);
    P_matrix_.at<double>(2,3) = t_matrix.at<double>(2);
}`

is this converted to this or did i messed it up?

`public void SetMatrixProjection(Mat r, Mat t)
    {
        matrixProjection.put(0, 0, r.get(0, 0));
        matrixProjection.put(0, 1, r.get(0, 1));
        matrixProjection.put(0, 2, r.get(0, 2));
        matrixProjection.put(1, 0, r.get(1, 0));
        matrixProjection.put(1, 1, r.get(1, 1));
        matrixProjection.put(1, 2, r.get(1, 2));
        matrixProjection.put(2, 0, r.get(2, 0));
        matrixProjection.put(2, 1, r.get(2, 1));
        matrixProjection.put(2, 2, r.get(2, 2));
        matrixProjection.put(0, 3, t.get(0, 0));
        matrixProjection.put(1, 3, t.get(1, 0));
        matrixProjection.put(2, 3, t.get(2, 0));
    }`

Also, in this case

`// Set up Ray
    Ray R((cv::Point3f)C_op, (cv::Point3f)ray);`

is the equivalent this?

`Ray r = new Ray(new Point3(cop.get(0, 0)[0], cop.get(1, 0)[0], cop.get(2, 0)[0]),
                        new Point3(ray.get(0, 0)[0], ray.get(1, 0)[0], ray.get(2, 0)[0]));`

Lastly

`point2d.x = (float)(point2d_vec.at<double>(0) / point2d_vec.at<double>(2));
    point2d.y = (float)(point2d_vec.at<double>(1) / point2d_vec.at<double>(2));`

is it converted to this?

`result.x = (float)(vec2D.get(0, 0)[0] / vec2D.get(2, 0)[0]);
        result.y = (float)(vec2D.get(1, 0)[0] / vec2D.get(2, 0)[0]);`

Much appreciated!

**Comment by tv-gc** [comment]
I am asking because i cannot make the detection work like the example, i have tried multiple ways and nothing works.

May i ask, is there plans of porting this example to OpenCVForUnity by any chance?

Thanks!

**Comment by EnoxSoftware** [comment]
Unfortunately, we have no plans to port this tutorial code to OpenCVForUnity.
Our MarkerLessARExample uses the same technology as the above tutorial and may be helpful for your development.
https://github.com/EnoxSoftware/MarkerLessARExample
