### ISSUE TITLE
Question about commercial use of YOLOv7 sample code

### ISSUE THREAD

**Issue by noCamelCase** [EnoxSoftware/OpenCVForUnity#174]
*This text was generated via translation so may contain slight inaccuracies.*

Hi.

This repository contains sample code using YOLOv7, but the YOLOv7 library is licensed under GPL 3.0.

If I purchase your middleware and create an application using this YOLOv7 sample code, can I commercially distribute the application I built?

My understanding is that anything using GPL 3.0 code needs to be licensed under GPL 3.0 as well. So I want to confirm if applications built with your middleware + YOLOv7 sample code can still be commercially licensed and distributed, or if they would need to be open sourced under GPL 3.0.

Please advise on the commercial licensing considerations when combining your proprietary middleware with GPL 3.0 code like YOLOv7. I want to ensure we comply with all license requirements before distributing our application commercially.

Thank you for your help clarifying this!

**Comment by EnoxSoftware** [comment]
Hello,

We just noticed that the license of YOLOv7 was clarified as GPL 3.0 by the author last July.
Thanks for letting us know.
We will be separating the YOLOv7 examples from our assets in the next version.

Regarding your question about whether or not YOLOv7 trained models under the GPL 3.0 license can be used commercially, we do not have enough knowledge to give you a definite answer.
Regarding the commercial use of the GPL 3.0 license, the answer in the YOLOv5 repository issues may be helpful.
https://github.com/ultralytics/yolov5/issues/5710#issuecomment-1659044685

**Comment by noCamelCase** [comment]
Thank you for the quick response.

I see, avoiding GPL license while using YOLOv7 does seem quite difficult.

While unfortunate, I think we will either use the YOLOX sample instead, or try to integrate yolo-nas into Unity as a workaround.

Thank you again for clarifying about the licensing concerns around commercial use of YOLOv7. Your answer was very helpful.
