### ISSUE TITLE
Update request for Unity5

### ISSUE THREAD

**Issue by makoto-unity** [EnoxSoftware/OpenCVForUnity#2]
I tried to use OpenCV on Unity5 for iOS. I built for iOS, but then, it crashed.
Both IL2CPP and Mono compiled app crashed.

Could you update this assets to Unity5?

**Comment by EnoxSoftware** [comment]
Thank you for a question.

"OpenCV for Unity 1.0.9(Support for Unity5)" is in pending review now in AssetStore.
I think that it is approved a few days later.

**Comment by makoto-unity** [comment]
Great! 
I'm looking forward it!
