### ISSUE TITLE
OpenCVForUnity' could not be found.

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [EnoxSoftware/OpenCVForUnity#21]
I clone the repo and it downlaoded compleely but getting this error:

> Assets/OpenCVForUnity/Examples/Advanced/HandPoseEstimationExample/ColorBlobDetector.cs(5,7): error CS0246: The type or namespace name `OpenCVForUnity' could not be found. Are you missing an assembly reference?

How can i solve it ? There is not documentation available.

**Comment by EnoxSoftware** [comment]
Have you imported OpenCVforUnity from AssetStore?
https://www.assetstore.unity3d.com/#!/content/21088

**Comment by MuhammadFaizanKhan** [comment]
No, I didn't import this asset from asset store. I just cloned the github project and getting this error. what is the difference b/w both? Do i need to use both? in which order? whats the difference?

Thanks for the reply.

**Comment by EnoxSoftware** [comment]
This repository is an example code included in OpenCVforUnity which is sold in AssetStore.https://www.assetstore.unity3d.com/#!/content/21088
In order to run this example code, you need to purchase OpenCVforUnity.

**Comment by MuhammadFaizanKhan** [comment]
Ok, Thanks. So first i have to purchase the package and need to include in this example project. But it seems that your package lack of significant documentation. Anyway thanks
