### ISSUE TITLE
Opencvforunity and unity 2017

### ISSUE THREAD

**Issue by bevrproject** [EnoxSoftware/OpenCVForUnity#22]
**Opencvforunity: Creation of mat worked perfectly fine in Unity 5 series. Now, we are working on unity 2017.3 and now mat object of the desired size is not getting created.**
for example: Mat img=new Mat(480,480,CvType.CV_8UC3);
if we check the size of Mat it returns 0 or Null.
Function: Utils.matToTexture2D(f8UC3,imgTexture); 
We get the exception: "ArgumentException: The output Texture2D object has to be of the same size
OpenCVForUnity.Utils.matToTexture2D (OpenCVForUnity.Mat mat, UnityEngine.Texture2D texture2D, UnityEngine.Color32[] bufferColors) (at Assets/OpenCVForUnity/org/opencv/unity/Utils.cs:303)
CameraDisplay.LateUpdate () (at Assets/CameraDisplay.cs:103)
"

**Comment by bevrproject** [comment]
​First our project was on unity version 5.3.
Now, we are working on unity version 2017.3.
OpenCVforUnity version: 1.2.3 and 3.0.0beta7
OS: Windows 10 and Windows 7.
​
 Demo2 - Copy.zip
<https://drive.google.com/file/d/1DbGJiDTAWTRBaMTbyJ4yNYL8XKiD_TXs/view?usp=drive_web>
​

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_5641366923078872616_m_6757478505919649228_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by EnoxSoftware** [comment]
OpenCVforUnity version: 1.2.3 does not support Unity 2017.
Please use the latest version of OpenCVforUnity.

**Comment by EnoxSoftware** [comment]
OpenCVforUnity v2.2.5 supports for Unity 2017.

**Comment by bevrproject** [comment]
I'm a student from India working on a project. OpenCVforUnity v2.2.5 costs
95$ in asset store which is way costly for me. Could you help me in this
matter??

**Comment by bevrproject** [comment]
Sir, could you please reply as soon as possible?

**Comment by EnoxSoftware** [comment]
Sorry, there are no educational or trial licenses.
