### ISSUE TITLE
OpenCVForUnity.Net, .MultiTrack and .MatOfRect2D seem to be missing from the main OpenCVForUnity

### ISSUE THREAD

**Issue by UnNeill** [EnoxSoftware/OpenCVForUnity#24]
Hey,

I'm trying to compile the examples (mainly the MobileNet SSD, Caffe, Tensor stuff) from this repo (2.2.8) with the OpenCVForUnity i downloaded from the asset store (also says 2.2.8) and these three packages seem to be missing, i do seem them on the documentation page.

I also have to fix the return type of several methods to get it to compile (vs2017, unity 2017.3.1), but everything else seems to work.

**Comment by EnoxSoftware** [comment]
All files in this repository are included in the OpenCVForUnity package downloaded from the asset store.
Please import OpenCVforUnity from the asset store into a new empty project.
In that case, does an error occur?

**Comment by UnNeill** [comment]
Hello,

yes, when i create a new project in 2017.3.1, import openCVForUnity 2.2.8 from asset store and then copy the files from the OpenCVForUnityExamples from github, it says it can't find Net, MultiTracker or MatOfRect2d.

Assets/OpenCVForUnity/Examples/ContribModules/tracking/TrackingExample/TrackingExample.cs(44,9): error CS0246: The type or namespace name `MultiTracker' could not be found. Are you missing an assembly reference?

Assets/OpenCVForUnity/Examples/ContribModules/tracking/TrackingExample/TrackingExample.cs(49,9): error CS0246: The type or namespace name `MatOfRect2d' could not be found. Are you missing an assembly reference?

Assets/OpenCVForUnity/Examples/MainModules/dnn/CaffeExample/MobileNetSSDWebCamTextureExample.cs(59,9): error CS0246: The type or namespace name `Net' could not be found. Are you missing an assembly reference?
...ResnetSSDFaceDetectionExample.cs(44,9): error CS0246:
...TensorFlowWebCamTextureExample.cs(46,9):
...YoloObjectDetectionWebCamTextureExample.cs(44,9):


the compilation errors are 
Assets/OpenCVForUnity/org/opencv/structured_light/GrayCodePattern.cs(95,20): error CS0037: Cannot convert null to `long' because it is a value type

Assets/OpenCVForUnity/org/opencv/xfeatures2d/DAISY.cs(63,7): error CS0126: An object of a type convertible to `OpenCVForUnity.DAISY' is required for the return statement
(and for FREAK,LATCH,LUCID,SIFT and SURF)

thanks for the reply
chris

**Comment by EnoxSoftware** [comment]
If you want to try the OpenCVForUnity example you do not need to copy the file of this repository after importing OpenCVForUnity from the asset store.All files in this repository are included in the package of AssetStore.("OpenCVForUnity / Assets / OpenCVForUnity / Examples /" and this repository file are the same file.)

**Comment by UnNeill** [comment]
I want to compile the c# script "https://github.com/EnoxSoftware/OpenCVForUnity/blob/master/Assets/OpenCVForUnity/Examples/MainModules/dnn/CaffeExample/MobileNetSSDWebCamTextureExample.cs"

This file is not in the OpenCVForUnity in the Asset Store, it is only in this Github repo.

on line 59 it says "Net net;".  There is no "Net" in the OpenCVForUnity namespace.  
Where can I find the file that contains the "OpenCVForUnity.Net" class? and MultiTrack and MatOfRect2d?

Your docs say it's in there, but I cant find it to compile the examples.
http://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_net.html
http://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_multi_tracker.html
http://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_mat_of_rect2d.html

**Comment by UnNeill** [comment]
I think you mentioned that there should be an "Examples" folder in the asset store version.  Asset store says there is one, but I dont see one in the actual package.
![image](https://user-images.githubusercontent.com/8339824/38646799-4ceb6eb6-3d9e-11e8-8b0a-03a028a2da9a.png)

It seems that I am getting an older version from the asset store.  The Examples folder is missing and Core.cs says that it's 3.1.0.
The MacOS libs are also 3.1.0

**Comment by UnNeill** [comment]
Old version is the problem.
Ive switched Unity accounts but it let me grab the old one from my previous account, I'm talking to them about switching this from my scrogbot account to my chrisrogers3d account.
