### ISSUE TITLE
IndexOutOfRangeException in ChArUcoBoard tracking example

### ISSUE THREAD

**Issue by theGiallo** [EnoxSoftware/OpenCVForUnity#31]
In vanilla example `ArUcoWebCamTextureExample` i get:
```IndexOutOfRangeException: Array index is out of range.
OpenCVForUnityExample.ARUtils.ConvertTvecToPos (System.Double[] tvec) (at Assets/OpenCVForUnity/Examples/ContribModules/aruco/ArUcoExample/ARUtils.cs:40)
OpenCVForUnityExample.ARUtils.ConvertRvecTvecToPoseData (System.Double[] rvec, System.Double[] tvec) (at Assets/OpenCVForUnity/Examples/ContribModules/aruco/ArUcoExample/ARUtils.cs:52)
OpenCVForUnityExample.ArUcoWebCamTextureExample.UpdateARObjectTransform (OpenCVForUnity.Mat rvec, OpenCVForUnity.Mat tvec) (at Assets/OpenCVForUnity/Examples/ContribModules/aruco/ArUcoExample/ArUcoWebCamTextureExample.cs:661)
OpenCVForUnityExample.ArUcoWebCamTextureExample.EstimatePoseChArUcoBoard (OpenCVForUnity.Mat rgbMat) (at Assets/OpenCVForUnity/Examples/ContribModules/aruco/ArUcoExample/ArUcoWebCamTextureExample.cs:634)
OpenCVForUnityExample.ArUcoWebCamTextureExample.Update () (at Assets/OpenCVForUnity/Examples/ContribModules/aruco/ArUcoExample/ArUcoWebCamTextureExample.cs:562)
```

Also in `UpdateARObjectTransform( Mat rvec, Mat tvec )` I get that rvec and tvec have both rows and cols equal to 1 in the working case of CanonicalMarker, and the  array returned by `.get(0,0)` has length 3. With ChArUcoBoard they are 1 cols by 3 rows, and the  array returned by `.get(0,0)` has length 1.

**Comment by EnoxSoftware** [comment]
Thank you very much for reporting.

Please change the code as follows.

https://github.com/EnoxSoftware/OpenCVForUnity/blob/master/Assets/OpenCVForUnity/Examples/ContribModules/aruco/ArUcoExample/ArUcoWebCamTextureExample.cs#L658-L684

        private void UpdateARObjectTransform (Mat rvec, Mat tvec)
        {
            // Convert to unity pose data.
            double[] rvecArr = new double[3];
            rvec.get(0, 0, rvecArr);
            double[] tvecArr = new double[3];
            tvec.get(0, 0, tvecArr);
            PoseData poseData = ARUtils.ConvertRvecTvecToPoseData (rvecArr, tvecArr);

            // Changes in pos/rot below these thresholds are ignored.
            if (enableLowPassFilter) {
                ARUtils.LowpassPoseData (ref oldPoseData, ref poseData, positionLowPass, rotationLowPass);
            }
            oldPoseData = poseData;

            // Convert to transform matrix.
            ARM = ARUtils.ConvertPoseDataToMatrix (ref poseData, true, true);

            if (shouldMoveARCamera) {

                ARM = arGameObject.transform.localToWorldMatrix * ARM.inverse;

                ARUtils.SetTransformFromMatrix (arCamera.transform, ref ARM);

            } else {

                ARM = arCamera.transform.localToWorldMatrix * ARM;

                ARUtils.SetTransformFromMatrix (arGameObject.transform, ref ARM);
            }
        }


Regerds,
EnoxSoftware

**Comment by theGiallo** [comment]
Thanks!
