### ISSUE TITLE
Videoio.CAP_PROP_FRAME_COUNT always returns 1 in iOS Build

### ISSUE THREAD

**Issue by maja3d** [EnoxSoftware/OpenCVForUnity#34]
I'm trying to get the value of CAP_PROP_FRAME_COUNT.
It always return 1 no matter what video I open.

In UnityEditor build it returns the correct value,
when I build for iOS it always return 1.

What could be the reason?

This is my code for reference:
```
VideoCapture cap = new VideoCapture();
cap.open(path);
int max_frames = (int)cap.get(Videoio.CAP_PROP_FRAME_COUNT);
```

Your reply would be appreciated.

**Comment by maja3d** [comment]
It works on 768x576_mjpeg.mjpeg.
The video I tested is captured using an iPhone. It works on Unity but when I build for iOS, it doesn't work.

Can you share the limitations on iOS and Android build?
And what can you suggest to support videos recorded using phone camera?
Appreciate the support.

**Comment by EnoxSoftware** [comment]
What format is the video captured using an iPhone?

https://github.com/opencv/opencv_extra/blob/master/testdata/cv/video/768x576.avi
I converted this video file to mjpeg codec video file using ffmpeg.

ffmpeg -i 768x576.avi -r 10 -s 768x576 -vcodec mjpeg -an 768x576_mjpeg.mjpeg

**Comment by maja3d** [comment]
The format is MOV.
I tried to convert it to mjpeg using ffmpeg but when I put it in Unity, it doesn't play.

**Comment by maja3d** [comment]
I downloaded the video from this link:
https://github.com/opencv/opencv_extra/blob/master/testdata/cv/video/768x576.avi
and converted it using this command:
ffmpeg -i 768x576.avi -r 10 -s 768x576 -vcodec mjpeg -an maja_mjpeg.mjpeg
[mjpeg.zip](https://github.com/EnoxSoftware/OpenCVForUnity/files/2799659/mjpeg.zip)

The mjpeg file is not read by Unity in StreamingAssets (Application.streamingAssetsPath+"/maja_mjpeg.mjpeg")
NullReferenceException: Object reference not set to an instance of an object

**Comment by maja3d** [comment]
Hello,

I tried donwloading different mjpeg files on the internet but none of them can be opened in Unity.
Only the original MJPEG file from you can be played.
The avi file from your link, converted to mjpeg using ffmpeg doesn't work as well.

Please respond.

**Comment by EnoxSoftware** [comment]
Thank you very much for reporting.
Could you try the following procedure?

1. ffmpeg -i 768x576.avi -r 10 -s 768x576 -vcodec mjpeg -an maja_mjpeg.**avi** 
2. Change the output file name from maja_mjpeg.**avi** to maja_mjpeg.**mjpeg**.

When the file name is maja_mjpeg.**avi**, I could not get the value of CAP_PROP_FRAME_COUNT well.

**Comment by maja3d** [comment]
Already tried that if you read my comment 2 days ago.
I even attached the files on my comment (original avi from you and the result mjpeg).

maja_mjpeg.mjpeg cannot be opened by VideoCapture.open()

**Comment by maja3d** [comment]
Same output. 
capture.isOpened() is false.
