### ISSUE TITLE
Older version of OpenCVForUnity (ver 2.3.2)

### ISSUE THREAD

**Issue by maja3d** [EnoxSoftware/OpenCVForUnity#35]
Hi,

Can I get an older version of OpenCVForUnity (ver 2.3.2)?
https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_video.html
I really need to use the function estimateRigidTransform.
After testing it in OpenCV C++, the result of estimateRigidTransform is better than estimateAffine2D.
I'm using it for video stabilization.

estimateRigidTransform is deprecated in the latest version.

**Comment by EnoxSoftware** [comment]
I think this post will be useful.
http://answers.opencv.org/question/123476/estimateaffinepartial2d-and-estimateaffine2d/
estimateAffinePartial2d is similar to estimateRigidTransform with the parameter fullAffine = false
estimateAffine2d is similar to estimateRigidTransform with the parameter fullAffine = true.

**Comment by maja3d** [comment]
Thank you for the information.
The output of estimate**Partial**Affine2d is worse than estimateAffine2d.

**Comment by EnoxSoftware** [comment]
Could you tell me your purchase infomation(OpenCV for Unity)? I will send you the download link of OpenCVForUnity 2.3.2. https://enoxsoftware.com/opencvforunity/contact/other-inquiry/
mail address using AssetStore :
invoice No :
![invoice_no](https://user-images.githubusercontent.com/7920392/52205541-b8256f80-28ba-11e9-8abf-3b2564693309.png)
