### ISSUE TITLE
Using yolo on hololens

### ISSUE THREAD

**Issue by valavakilian** [EnoxSoftware/OpenCVForUnity#37]
Hi I was just wondering if it is possible to use this library for developing Hololens application for object detection using yolo ?
thank you for the support

**Comment by EnoxSoftware** [comment]
Thank you for your inquiry.

The OpenCV Dnn module is not supported by the UWP platform of OpenCV C++, so there is no plan to be implemented by OpenCVforUnity for now.
https://github.com/opencv/opencv/blob/master/modules/dnn/CMakeLists.txt#L1-L3
https://enoxsoftware.com/opencvforunity/documentation/support-modules/


Regerds,
EnoxSoftware

**Comment by joaocc** [comment]
@EnoxSoftware Do you happen to know why (or have pointers to discussions on that) isn't the DNN module available on UWP? Thanks

**Comment by EnoxSoftware** [comment]
@joaocc https://github.com/EnoxSoftware/OpenCVForUnity/issues/32#issuecomment-516325052

**Comment by cwule** [comment]
It seemed to work on OpenCV 3.2.0. Is it possible to add that version?
["the DNN module shipped with 3.2.0 opencv_contrib outputs correct probabilities in both win32 and UWP however"](https://github.com/opencv/opencv/issues/9177).

**Comment by raulsf6** [comment]
@cwule Actually I managed to run DNN module on a UWP project in Unity wth good results using the Free Trial version. However when I switched to the paid version it did not work becaus eit cannot find the DNN module. Give a check to issue #92
