### ISSUE TITLE
Is there a reason that the SimpleBlobDetector class is not wrapped?

### ISSUE THREAD

**Issue by MattijsKneppers** [EnoxSoftware/OpenCVForUnity#38]
It looks like [SimpleBlobDetector](https://docs.opencv.org/master/d0/d7a/classcv_1_1SimpleBlobDetector.html), that is part of the OpenCV 4.0.x package, is not in OpenCVforUnity. Is this intentional or could this be an oversight?

**Comment by MattijsKneppers** [comment]
Interestingly, you did seem to have wrapped a [Params](https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_features2d_module_1_1_params.html) class that seems to be the equivalent of [cv::SimpleBlobDetector::Params](https://docs.opencv.org/4.0.0/d8/da7/structcv_1_1SimpleBlobDetector_1_1Params.html) in OpenCV. As far as I can see it is useless without having a SimpleBlobDetector. In OpenCVForUnity it doesn't seem to be used anywhere. Also, it is in the Features2dModule namespace instead. 

Maybe I am missing something though, in that case it would be great if you could point me in the right direction.

**Comment by EnoxSoftware** [comment]
Since this package is a clone of OpenCV Java, you are able to use the same API as OpenCV Java 4.0.0. So, SimpleBlobDetector class is not supported for now. 
The Params class is currently never used as you pointed out. I plan to fix this bug in a future version. https://docs.opencv.org/4.0.0/javadoc/org/opencv/features2d/Params.html
Also,
Since OpenCV is open source, it is possible to refer to SimpleBlobDetector's algorithm.
https://github.com/opencv/opencv/blob/master/modules/features2d/src/blobdetector.cpp

**Comment by MattijsKneppers** [comment]
Thanks for the quick reply and for clarifying, it is especially useful to know that looking at the Java version docs is most useful to understand the Unity port.

**Comment by rubentorresbonet** [comment]
Did you manage to port it @MattijsKneppers ? I am in need of that class. Thanks

**Comment by MattijsKneppers** [comment]
I did, however I'd need to properly test it for more general use and maybe make an example before I do a pull request. Or I could just do a pull request with the file as is and leave it up to the authors to test and integrate. @EnoxSoftware would you have a preference?

**Comment by rubentorresbonet** [comment]
I can definitely help with testing with my use case if you share a PR or temporal pastebin.

**Comment by MattijsKneppers** [comment]
Here are the files in a zip, just taken straight out of the project without any testing:

[SimpleBlobDetector.zip](https://github.com/EnoxSoftware/OpenCVForUnity/files/3152876/SimpleBlobDetector.zip)

**Comment by rubentorresbonet** [comment]
The biggest flaw I found was the findblob is using the input image and not its binary version. After fixing that I got some results. However, the python implementation is quite superior. I didnt have time to pinpoint exactly where the issue comes from.

**Comment by MattijsKneppers** [comment]
>  findblob is using the input image and not its binary version

Hey, nice catch! It worked for me, but now it will likely work better. In fact I don't see why the original image is passed in at all in the original code. 

For the archives here is the fixed version. [SimpleBlobDetector V2.zip](https://github.com/EnoxSoftware/OpenCVForUnity/files/3166059/SimpleBlobDetector.V2.zip)

> However, the python implementation is quite superior

I tried to do a literal port of the [original code](https://github.com/opencv/opencv/blob/master/modules/features2d/src/blobdetector.cpp), but if you ever find out what is different that makes the python version work better, I'd love to know!

**Comment by ZyanyaNochipa** [comment]
Hi @MattijsKneppers  

Thanks for your work, it works for me.
