### ISSUE TITLE
Build error when building for WebGL ('z_inflateInit2_': symbol multiply defined!ERROR:root:Failed to run llvm optimizations:)

### ISSUE THREAD

**Issue by ashish24rawat** [EnoxSoftware/OpenCVForUnity#41]
`Failed running "D:\Unity Installs\2019.1.2f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten_Win\python\2.7.5.3_64bit\python.exe" -E "D:\Unity Installs\2019.1.2f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emcc" @"D:\Projects\2019WebGLTest\Assets\..\Temp\emcc_arguments.resp"

stdout:
stderr:error: Linking globals named 'z_inflateInit2_': symbol multiply defined!ERROR:root:Failed to run llvm optimizations:
UnityEngine.GUIUtility: ProcessEvent(Int32, IntPtr)`

Using Unity 2018.4.3f1

**Comment by EnoxSoftware** [comment]
Thank you very much for reporting.
This error seems to occur in the latest version of Unity2018. This error will be fixed in the next version of OpenCVForUnity.
For now, please use Unity2019.1 or later.
