### ISSUE TITLE
Unable to get it working on Android 64bit architecture

### ISSUE THREAD

**Issue by jungleeToofan** [EnoxSoftware/OpenCVForUnity#42]
Hi,
We've been using the DLib face tracker and OpenCV library successfully in  the 32bit architecture. However, since google play store has mandated 64 bit architectures from 1st August onward, we need to build using the same.

However we are finding that it doesn't work on 64 bit devices. Unity doesn't throw any errors during building and the app even asks for permission to access the camera but then isn't able to capture/display video from the camera.

**Comment by EnoxSoftware** [comment]
Thank you very much for reporting.

Could you tell me about your test environment?
OpenCVForUnity version : 
Unity version :

**Comment by jungleeToofan** [comment]
Never mind, found the solution: Goto OpenCVForUnity/Plugins/libs/ and for each plugin make sure 'Android' is enabled and the correct CPU type is selected.
