### ISSUE TITLE
Video feed issue on IL2CCP 

### ISSUE THREAD

**Issue by Visheee** [EnoxSoftware/OpenCVForUnity#43]
Hi 
I tried to build HandPoseEstimationExample while compiling for Mono it is working fine means I am able to get the camera feed but when I compile for IL2CPP the camera feed is not working it shows a blank screen. Can you please help me with this?
![Screenshot_20190812-044503_Nottingham](https://user-images.githubusercontent.com/37211624/62840705-7851a180-bcbc-11e9-9e1b-f77b688c365f.jpg)

**Comment by EnoxSoftware** [comment]
Thank you very much for reporting.

Could you tell me about your environment?
OpenCVForUnity version : 
Build platform : 


Regards,
Enox Software

**Comment by Visheee** [comment]
Hi, Thank you for reaching out.

OpenCVForUnity version: 2.3.6 
Build Platform: Android

**Comment by EnoxSoftware** [comment]
Is ImportSettings of "arm64-v8a / libopencvforunity.so" set correctly?

![arm64_1](https://user-images.githubusercontent.com/7920392/62921664-4dfb0380-bde4-11e9-86d1-ebe866574a8d.png)
![arm64_2](https://user-images.githubusercontent.com/7920392/62921671-505d5d80-bde4-11e9-8afb-d1f4b0ea0288.png)

**Comment by Visheee** [comment]
Thank you soo much for your help really appreciated.
