### ISSUE TITLE
Possible bug in Converters.cs

### ISSUE THREAD

**Issue by warpdriv** [EnoxSoftware/OpenCVForUnity#47]
Hi,

I have purchased this product off the Unity Asset Store and came across a possible bug in org.opencv.utils.Converters.cs

From the method starting on 637. It would seem that this block would always throw, because if you take line 639 and line 645, no matter what m is, it will throw. So in my source I commented out 639 and 640 to get passed it. Can you please let me know if my assumptions are correct?

Thank you.

```
637 public static void Mat_to_vector_vector_Point(Mat m, List<MatOfPoint> pts)
638        {
639      if (m != null)
640            m.ThrowIfDisposed();
641
642      if (pts == null)
643             throw new CvException("Output List can't be null");
644
645      if (m == null)
646           throw new CvException("Input Mat can't be null");

            List<Mat> mats = new List<Mat>(m.rows());
            Mat_to_vector_Mat(m, mats);
            foreach (Mat mi in mats)
            {
                MatOfPoint pt = new MatOfPoint(mi);
                pts.Add(pt);
                mi.release();
            }
            mats.Clear();
        }
```

**Comment by EnoxSoftware** [comment]
“ｍ.ThrowIfDisposed ()” throws an exception only if m is already Disposed.
