### ISSUE TITLE
(iOS) IPA processing failed 

### ISSUE THREAD

**Issue by Macoron** [EnoxSoftware/OpenCVForUnity#49]
Trying to create IPA with enterprise signature. It fails every time on Xcode 11.1 and OpenCV 2.3.7.  Logs doesn't print anything interesting except:
`/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool exited with 1`
Tried to disable bitcode from issue #40 - didn't help.
<img width="764" alt="Screenshot 2019-10-31 at 16 18 53" src="https://user-images.githubusercontent.com/6161335/67950224-59e3ae00-fbfa-11e9-99c9-2947d8917dcd.png">

Xcode 10.3 works great though.

**Comment by EnoxSoftware** [comment]
Is the Unity version you tested compatible with Xcode11.1?

**Comment by Macoron** [comment]
To be honest - I'm not sure. It's 2018.3.12f1
When I change from .framework from "Embed and sign", to "Do not Embed" it archives fine. But app doesn't work. When I build directly to the phone, it works though.

**Comment by EnoxSoftware** [comment]
Unity2018.3.12f1 may not support Xcode11.1.
If you use Xcode 11.1, I recommend using the latest Unity version.

**Comment by Macoron** [comment]
Well, after some time, I finally found what was the problem.

In my company we use opencv wrapped in [unity package manager](https://docs.unity3d.com/Packages/com.unity.package-manager-ui@1.8/manual/index.html). If OpenCV is inside Assets folder of main project - all works great. If OpenCV is in a dependent package - it crushes on XCode 11 after IPA archiving.

I found [similar problem here ](https://stackoverflow.com/questions/57382217/how-to-fix-ipa-processing-failed-error-in-xcode-11). Looks like architecture striping doesn't work right. 

Right now I moved OpenCV to assets problem. Any idea for a better solution? Maybe some post-buid scripts that we should fix?

**Comment by EnoxSoftware** [comment]
Thank you very much for reporting.

Is there any difference in the configuration of the Xcode project that is output when using unity package manager?
It seems that the RemoveSimulatorArchitectures method of OpenCVForUnityIOSBuildPostprocessor.cs is not working properly.

`RemoveSimulatorArchitectures (path + "/Frameworks/"+opencvForUnityFolderPath+"Plugins/iOS/", "opencv2.framework/opencv2");`
Is the path to the Plugins folder correct?

**Comment by Macoron** [comment]
Yep, path changed to the package name (in our case it was something like com.opencv.opencvforunity). It looks like it copy package name from package manifest (which was created by us).

Anyway, we just changed this lines and it all started working again:
```
var file = Directory.GetDirectories(path, "*opencv2.framework", SearchOption.AllDirectories).FirstOrDefault();
if (string.IsNullOrEmpty(file))
    throw new System.Exception("Can't find opencv2.framework");
var directory = Path.GetDirectoryName(file);
RemoveSimulatorArchitectures (directory, "opencv2.framework/opencv2");
``` 

So it basically search for a .framework in a Xcode project. Now it works in a package and also in a regular assets folder.
Thanks for help!
