### ISSUE TITLE
Cannot create ad hoc build that includes OpenCV

### ISSUE THREAD

**Issue by samw3** [EnoxSoftware/OpenCVForUnity#5]
I am getting several errors when I try and submit a build to iTunes Connect.  Here are examples of the errors.

![screenshot 2015-04-30 22 40 46](https://cloud.githubusercontent.com/assets/231388/7426144/e7f46196-ef8c-11e4-8f38-b02b81c3c28e.png)
![screenshot 2015-04-30 22 40 46](https://cloud.githubusercontent.com/assets/231388/7426145/e7f51e9c-ef8c-11e4-88e6-5e3f93a7aade.png)

**Comment by macbthpsw** [comment]
Hi, I'm on the same project team as Sam.  Before this we were getting codesigning errors due to Unity's .meta files getting into the opencvforunity.bundle.  We deleted those and got much further in the build submission.  This is for an adhoc build, by the way.

**Comment by EnoxSoftware** [comment]
Report Thank you. Such error reporting is the first time.
This error occurs when you submit the Mac OSX App to iTunesConnect?

**Comment by samw3** [comment]
This is an iOS ad hoc build.  We are submitting to iTunesConnect for a TestFlight build.

**Comment by EnoxSoftware** [comment]
Do "opencvforunity.bundle" has been included in the xcode project?
There is no need to include the "opencvforunity.bundle" to xcode project for iOS.

**Comment by macbthpsw** [comment]
Thanks, removing opencvforunity.bundle fixed the problem.
