### ISSUE TITLE
How to detect hand gesture including each finger from web camera?

### ISSUE THREAD

**Issue by peterchen2001** [EnoxSoftware/OpenCVForUnity#50]
Hi,
With Opencvforunity, how to detect hand gesture including each finger from web camera? Thanks in advance if you can give any clues or code snippet for me.

**Comment by EnoxSoftware** [comment]
HandPoseEstimationExample is included in OpenCVForUnity.
https://github.com/EnoxSoftware/OpenCVForUnity/tree/master/Assets/OpenCVForUnity/Examples/Advanced/HandPoseEstimationExample
![HandPoseEstimationExample](https://user-images.githubusercontent.com/7920392/68302631-c15f9900-00e5-11ea-8153-0a71934b804a.png)

**Comment by peterchen2001** [comment]
Great job!
