### ISSUE TITLE
About the necessity of cvtColor after the imread

### ISSUE THREAD

**Issue by mt19a005** [EnoxSoftware/OpenCVForUnity#65]
Sorry for my poor English and newbie OpenCV For Unity user.
I try load the image for ```imread``` and paste the image to ```GetComponent<Renderer>().material.mainTexture```  after the ```matToTexture2D```,
but displayed Image is  blue tint .
That is difference behavior when I was using OpenCV in C++.
If use ```cvtColor``` after ```imread```, it look source image.
How do I make it look the real image without using ```cvtColor```?

Source code
```
public class test : MonoBehaviour
{
    Mat src1;
    Texture2D dst2D;

    // Start is called before the first frame update
    void Start()
    {
        src1 = Imgcodecs.imread(Application.dataPath + "/Resources/a.jpg");
        //Imgproc.cvtColor(src1, src1, Imgproc.COLOR_RGBA2BGRA);

        dst2D = new Texture2D(src1.cols(), src1.rows());
        Utils.matToTexture2D(src1, dst2D);
        gameObject.GetComponent<Renderer>().material.mainTexture = dst2D;
    }
}
```
Thank you in advance

**Comment by EnoxSoftware** [comment]
https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56
_In the case of color images, the decoded images will have the channels stored in B G R order._

The Mat data obtained by the Imread method is in BGR order. In contrast, Texture2D data is in RGB order, so you need to call the Imgproc.cvtColor method.

**Comment by mt19a005** [comment]
Thanks for reply.
I understand. 
Thank you🤗🤗
