### ISSUE TITLE
How I can do face recognition?

### ISSUE THREAD

**Issue by datomnurdin** [EnoxSoftware/OpenCVForUnity#7]
As per subject, is it possible to do face recognition using OpenCVForUnity which is comparing it with existing database to check either is it match or not. Please advice. Thank you.

**Comment by EnoxSoftware** [comment]
Please refer to FaceRecognizerSampleScene.
https://github.com/EnoxSoftware/OpenCVForUnity/blob/master/Samples/FaceRecognizerSample/FaceRecognizerSample.cs
FaceRecognizer Class API
http://enoxsoftware.github.io/OpenCVForUnity/doc/html/class_open_c_v_for_unity_1_1_face_recognizer.html#ac76873c53b8a2ae2de48ba381bc8f763
