### ISSUE TITLE
The videoio Gstreamer module added in version 2.4 does not work 

### ISSUE THREAD

**Issue by hitch22** [EnoxSoftware/OpenCVForUnity#70]
Howdy,

I noticed that the updated version 2.4 has videoio Gstreamer module enabled and also included in the documentation.
I am testing out the module to see if I could stream video from a HoloLens2 device to a server.

I tested out a pipeline, made sure it worked, and used it as follows:

HL2 Client

VideoWriter vw = new VideoWriter("appsrc ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! udpsink host=192.168.0.100 port=5000", Videoio.CAP_GSTREAMER, 0, 20, new Size(640,480), true);
vw.write(preview);

Gstreamer Server

udpsrc port=5000 caps = "application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)96" ! rtph264depay ! decodebin ! videoconvert ! appsink

However, I find that it does not do anything. What am I doing wrong?

**Comment by EnoxSoftware** [comment]
In OpenCVForUnity 2.4.0, gstreamer is not enabled by default.
OpenCVForUnity has a way to use the OpenCV library with modified build parameters.
For more details, see the section on “How to use OpenCV Dynamic Link Library with customized build settings” in ReadMe.pdf.
I have confirmed that the Gstreamer-enabled dynamic library works on the Windows platform, but I have not yet confirmed it on UWP.

**Comment by hitch22** [comment]
> In OpenCVForUnity 2.4.0, gstreamer is not enabled by default.
> OpenCVForUnity has a way to use the OpenCV library with modified build parameters.
> For more details, see the section on “How to use OpenCV Dynamic Link Library with customized build settings” in ReadMe.pdf.
> I have confirmed that the Gstreamer-enabled dynamic library works on the Windows platform, but I have not yet confirmed it on UWP.

I see. Thanks for clearing things up! I will look into customized build settings!
