### ISSUE TITLE
WebGL Mobile

### ISSUE THREAD

**Issue by GaryQuahVizioFly** [EnoxSoftware/OpenCVForUnity#75]
Hi, I was testing OpenCV build for WebGL, managed to make the build work on both PC and Android, but when it came to IOS, face detection didnt work / start. Tested using chrome. Any idea how to solve this?

**Comment by EnoxSoftware** [comment]
https://docs.unity3d.com/2018.1/Documentation/Manual/webgl-browsercompatibility.html
Note that Unity WebGL content is not currently supported on mobile devices. It may still work, especially on high-end devices, but many current devices are not powerful enough and don’t have enough memory to support Unity WebGL content well. For this reason, Unity WebGL shows a warning message when trying to load content on mobile browsers (which can be disabled if needed).
