### ISSUE TITLE
new Mat()

### ISSUE THREAD

**Issue by A00107408** [EnoxSoftware/OpenCVForUnity#80]
Trying to use OpenCV+Unity on the HoloLens 2 but when I try to create a new Mat(rows, cols type) I catch the exception: System.Int32 cols, System.Int32 type at OpenCvSharp.Mat..ctor(rows, cols, type).

new Mat(rows, cols, type) works fine for me in other projects with this library, but not on the HoloLens 2. Any suggestions appreciated.

**Comment by EnoxSoftware** [comment]
This repository is OpenCVForUnity, not OpenCV+Unity.
