### ISSUE TITLE
HoloLens 2 compatibility

### ISSUE THREAD

**Issue by A00107408** [EnoxSoftware/OpenCVForUnity#81]
Hi, is OpenCVForUnity compatible with UWP, IL2CPP and the HoloLens 2? If so, I will buy it.

**Comment by felixvh** [comment]
Is it compatible?

**Comment by EnoxSoftware** [comment]
Hi, Felix

Unfortunately, I don't have Hololens2 at hand and haven't tried it, but this thread already has a way to make my example work with Hololens2.
EnoxSoftware/HoloLensWithOpenCVForUnityExample#29

Best regards,
Enox Software
