### ISSUE TITLE
Mat set array

### ISSUE THREAD

**Issue by A00107408** [EnoxSoftware/OpenCVForUnity#88]
Does OpenCvForUnity have a method to iterate through a Mat and set all rgb pixel values like:

Mat.SetArray(width, height, double[r,g,b]); ??

**Comment by EnoxSoftware** [comment]
https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_core_module_1_1_mat.html#ad18e915ae5367254558ae21a1b45664c

mat.setTo( new Scalar( r, g, b));

**Comment by A00107408** [comment]
Nice. Thank you.
