### ISSUE TITLE
Where is constant CV_CAP_PROP_POS_FRAMES?

### ISSUE THREAD

**Issue by yosh8** [EnoxSoftware/OpenCVForUnity#9]
I want to use VideoCapture.set( ) for frame position seeking, 
but constant "CV_CAP_PROP_POS_FRAMES" does not exist.
(should not it exist in Highgui.cs?)

I think this is a issue, but how about?

**Comment by EnoxSoftware** [comment]
http://answers.opencv.org/question/56807/where-is-cv_cap_prop_pos_frames-in-java/
Please try to set  "1"(Constant value in videoio_c.h).
or
Please try to use the Beta Version of “OpenCV for Untiy” based on “OpenCV3.0.0-rc1”.
