### ISSUE TITLE
fastTextureToMat() not working for me.

### ISSUE THREAD

**Issue by A00107408** [EnoxSoftware/OpenCVForUnity#90]
_inTexture = new Texture2D(Width, Height, TextureFormat.BGRA32, false);
_myMat = new Mat(Height, Width, CvType.CV_8UC3);
_outTexture = new Texture2D(Width, Height, TextureFormat.BGRA32, false)

Utils.fastTexture2DToMat(_inTexture, _myMat);
Utils.fastMatToTexture2D(_myMat, _outTexture);

Produces the error: not enough data provided (will result in overread). This results in distorted output image. What am I doing wrong?

Any help appreciated.
Thank you.

**Comment by EnoxSoftware** [comment]
> The Mat object and the Texture2D object must have the same width, height, and **data format**.

https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_unity_utils_1_1_utils.html#a8cfe3501ab77618c7cd4f49ebe6b4cbd
https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_unity_utils_1_1_utils.html#a88cb8fa0a189a741e5b59172713760c1

If you change it as follows, it will probably work fine.

_inTexture = new Texture2D(Width, Height, TextureFormat.BGRA32, false);
_myMat = new Mat(Height, Width, CvType.CV_8UC**4**);
_outTexture = new Texture2D(Width, Height, TextureFormat.BGRA32, false)

Utils.fastTexture2DToMat(_inTexture, _myMat);
Utils.fastMatToTexture2D(_myMat, _outTexture);

**Comment by A00107408** [comment]
_inTexture = new Texture2D(Width, Height, TextureFormat.**RGB**A32, false);
_myMat = new Mat(Height, Width, CvType.CV_8UC4);
_outTexture = new Texture2D(Width, Height, TextureFormat.**RGB**A32, false)

works really well.

Thank you for the exact solution.
