### ISSUE TITLE
[Help!] How to encoded byte array to Mat?? 

### ISSUE THREAD

**Issue by YouMinJung** [EnoxSoftware/OpenCVForUnity#91]
Hi.
I want to send webcam image to another computer using UDP socket communication.
So I made the code using python.
The code is like below.

//////////////// Image Sender ////////////////
```
import socket
import cv2
import numpy

HOST = '127.0.0.1'
PORT = 9999

server_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
capture = cv2.VideoCapture(0)

while True:
    ret, frame = capture.read()

    if ret == False:
        continue

    encode_param = [int(cv2.IMWRITE_JPEG_QUALITY), 90]
    result, imgencode = cv2.imencode('.jpg', frame, encode_param)
    data = numpy.array(imgencode)
    stringData = data.tobytes()

    // send total image byte size
    server_socket.sendto(str(len(stringData)).encode(), (HOST, PORT))
    // send image data
    server_socket.sendto(stringData, (HOST, PORT))

    if key == 27:
        break

server_socket.close()
```

//////////////// Image Receiver ////////////////
```
import socket
import numpy as np
import cv2

HOST = '127.0.0.1'
PORT = 9999

client_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
client_socket.bind((HOST, PORT))

def recvall(sock, count):
    buf = b''
    while count:
        newbuf, addr = sock.recvfrom(count)
        if not newbuf: return None
        buf += newbuf
        count -= len(newbuf)

    return buf

while True:

    // receive total image size
    length, addr = client_socket.recvfrom(1024)

    // receive image data
    stringData = recvall(client_socket, int(length))
    data = np.frombuffer(stringData, dtype='uint8')
    decimg = cv2.imdecode(data, 1)
    cv2.imshow('Image', decimg)

    key = cv2.waitKey(1)
    if key == 27:
        break

client_socket.close()
```

However, I want to make this program using Unity (= OpenCvForUnity)
I received the byte array from another program but Error occured when I do byte[] -> Mat and then decoding.
////////// This is the Unity Code. ////////// 
```
byte[] received_all(IPEndPoint _endpoint, int _count)
{
    byte[] tmp_data = new byte[_count];
    tmp_data = server.Receive(ref ipep);
    return tmp_data;
}

// received total image byte size
byte[] data = new byte[1024];
data = server.Receive(ref ipep);
string received_data = Encoding.UTF8.GetString(data);

// receive image data            
byte[] byte_image = received_all(ipep, Convert.ToInt32(received_data));
int[] bytesAsInts = Array.ConvertAll(byte_image, c => (int)c);
            
Mat mat9 = new Mat(bytesAsInts, CvType.CV_8UC3, Scalar.all(0));
Mat img_result = Imgcodecs.imdecode(mat9, 1);
Imgcodecs.imwrite("sample.jpg", img_result);
```

I think these "**Mat mat9 = new Mat(bytesAsInts, CvType.CV_8UC3, Scalar.all(0)); Mat img_result = Imgcodecs.imdecode(mat9, 1); Imgcodecs.imwrite("sample.jpg", img_result);**" code occur error.

How to make proper program what I want?

**Comment by EnoxSoftware** [comment]
https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_imgcodecs_module_1_1_imgcodecs.html#ae9baf4e7f18f36bb6fc88b1362939f78

Could you try the following code?
```
// receive image data            
byte[] byte_image = received_all(ipep, Convert.ToInt32(received_data));
Mat buff = new Mat (1, byte_image.Length, CvType.CV_8UC1);
Utils.copyToMat<byte> (byte_image, buff);

Mat img_result = Imgcodecs.imdecode (buff, Imgcodecs.IMREAD_COLOR);
```

**Comment by YouMinJung** [comment]
Thank you for help.
However, I tried these code but still error occured.

original image size is 63058.
(original image is 640 x 480, 3 channel.)
byte[] byte_image size is 63058 and data is like below.
255 216 255 224 0 16 74 70 0 1 1 0 0 1 0 255 3 4 3 3 4 ... 255 217

When I did "Mat buff = new Mat (1, byte_image.Length, CvType.CV_8UC1);", Assertion failed on expression 'g_ThreadedGfxDevice' error occured.

What is the problem.....??

**Comment by EnoxSoftware** [comment]
> Assertion failed on expression 'g_ThreadedGfxDevice'

Initializing an OpenCVForUnity class outside of a Unity thread seems to cause this error.
Could you change the source code as follows?

        Mat buff;
        Mat img_result;

        // Use this for initialization
        void Start()
        {
            ----------------
            ----------------

            buff = new Mat (1, byte_image.Length, CvType.CV_8UC1);
            Utils.copyToMat<byte> (byte_image, buff);

            img_resul = Imgcodecs.imdecode (buff, Imgcodecs.IMREAD_COLOR);

            ----------------
        }

**Comment by YouMinJung** [comment]
Thank you!
Now It works well. Again thank you so much!
