### ISSUE TITLE
Make myself Marker Dictionary

### ISSUE THREAD

**Issue by qpaozixu** [EnoxSoftware/OpenCVForUnity#93]
ARUCO_MIP_36h12 is not support in this?

I only see these below.
public const int DICT_4X4_50 = 0;
public const int DICT_4X4_100 = 0 + 1;
public const int DICT_4X4_250 = 0 + 2;
public const int DICT_4X4_1000 = 0 + 3;
public const int DICT_5X5_50 = 0 + 4;
public const int DICT_5X5_100 = 0 + 5;
public const int DICT_5X5_250 = 0 + 6;
public const int DICT_5X5_1000 = 0 + 7;
public const int DICT_6X6_50 = 0 + 8;
public const int DICT_6X6_100 = 0 + 9;
public const int DICT_6X6_250 = 0 + 10;
public const int DICT_6X6_1000 = 0 + 11;
public const int DICT_7X7_50 = 0 + 12;
public const int DICT_7X7_100 = 0 + 13;
public const int DICT_7X7_250 = 0 + 14;
public const int DICT_7X7_1000 = 0 + 15;
public const int DICT_ARUCO_ORIGINAL = 0 + 16;
public const int DICT_APRILTAG_16h5 = 0 + 17;
public const int DICT_APRILTAG_25h9 = 0 + 18;
public const int DICT_APRILTAG_36h10 = 0 + 19;
public const int DICT_APRILTAG_36h11 = 0 + 20;

**Comment by EnoxSoftware** [comment]
You can use the custom_dictionary() method to create a custom dictionary.
https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_aruco_module_1_1_aruco.html#a7b5779f410edd753d6597d0ab9e3b8d8

Also,
opencv does not seem to support the ARUCO_MIP_36h12 dictionary.
ARUCO_MIP_36h12 dictionary
https://answers.opencv.org/question/177102/aruco-module-using-the-aruco_mip_36h12-dictionary/

**Comment by qpaozixu** [comment]
OK,  Thanks for your help :)

Enox Software <notifications@github.com> 於 2021年1月9日 週六 下午10:18寫道：
