### ISSUE TITLE
Video Player with Controller

### ISSUE THREAD

**Issue by oaishi** [EnoxSoftware/OpenCVForUnity#97]
Hello, 

I wanted to play a video with time scrub and controller in OpenCV unity. similar to this: https://youtube.com/watch?v=9LwOmMzOrp4&feature=share

Can you kindly tell me how I can do so?

**Comment by EnoxSoftware** [comment]
VideoCaptureExample allows you to control the frame control with a slider.
https://github.com/EnoxSoftware/OpenCVForUnity/blob/master/Assets/OpenCVForUnity/Examples/MainModules/videoio/VideoCaptureExample/VideoCaptureExample.cs
<img width="539" alt="VideoCaptureExample" src="https://user-images.githubusercontent.com/7920392/107200382-fa9a5d80-6a3a-11eb-9422-ff0e578e1302.PNG">

**Comment by oaishi** [comment]
Thank you so much! This was very helpful
