### ISSUE TITLE
Need to convert byte[] to Mat

### ISSUE THREAD

**Issue by A00107408** [EnoxSoftware/OpenCVForUnity#98]
// video feed from HoloLens2.
private byte[] _videoSourceImage;            
   
private Mat _videoSourceMat;
private Mat _rgbaMat;

_videoSourceMat = new Mat(imHeight, imWidth, CvType.CV_8UC4);
_rgbaMat = new Mat(imHeight, imWidth, CvType.CV_8UC3);

_videoSourceMat = Imgcodecs.imdecode(new MatOfByte(_videoSourceImage), Imgcodecs.IMREAD_UNCHANGED);
         
Imgproc.cvtColor(_videoSourceMat, _rgbaMat, Imgproc.COLOR_RGB2RGBA, 4);
           
Utils.fastMatToTexture2D(_rgbaMat, _processedTexture);
           
OutQuad.GetComponent<Renderer>().material.mainTexture = _processedTexture;

This code does not create an error, but just leaves the 'OutQuad' texture blank.

**Am I using Imgcodecs.imdecode() correctly or is there a better way of converting a byte[] to a Mat?**

(I use _rgbaMat to convert the Mat back to a texture2D for display in Unity because fastMatToTexture2D() needs the CV_8UC3 type.)

**Comment by EnoxSoftware** [comment]
Is the byte sequence in the video feed compressed? Or is it a sequence of bytes in uncompressed RGBA order?


https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_imgcodecs_module_1_1_imgcodecs.html#ae9baf4e7f18f36bb6fc88b1362939f78
Currently, the following file formats are supported:

Windows bitmaps - *.bmp, *.dib (always supported)
JPEG files - *.jpeg, *.jpg, *.jpe (see the Note section)
JPEG 2000 files - *.jp2 (see the Note section)
Portable Network Graphics - *.png (see the Note section)
WebP - *.webp (see the Note section)
Portable image format - *.pbm, *.pgm, *.ppm *.pxm, *.pnm (always supported)
PFM files - *.pfm (see the Note section)
Sun rasters - *.sr, *.ras (always supported)
TIFF files - *.tiff, *.tif (see the Note section)
OpenEXR Image files - *.exr (see the Note section)
Radiance HDR - *.hdr, *.pic (always supported)
Raster and Vector geospatial data supported by GDAL (see the Note section)

**Comment by A00107408** [comment]
I am taking the code straight from the camnewnham project (https://github.com/camnewnham/HoloLensCameraStream) that is used in the EnoxSoftware HoloLensWithOpenCVForUnityExample.

He used BGRA32 texture format, so I think it is uncompressed BGRA?

So I am not converting jpgs or anything. Each HoloLens video frame is coming in as a byte[], and I need to apply OpenCV filters to it as a Mat. 

So lets presume it is uncompressed BGRA if that makes any sense.

**Comment by EnoxSoftware** [comment]
An example of converting the byte array output by the HoloLensCameraStream plugin to Mat format can be found here.
https://github.com/EnoxSoftware/HoloLensWithOpenCVForUnityExample/blob/master/Assets/HoloLensWithOpenCVForUnityExample/Scripts/Utils/HololensCameraStreamToMatHelper.cs

**Comment by A00107408** [comment]
Of course. I forgot about this. Thank you.

**Comment by A00107408** [comment]
This is basically what I was looking for:

OpenCVForUnity.UtilsModule.MatUtils.copyToMat<byte>(image, _pvMat);
